/**
 * ClaimPacket sealing. The pinned vector is PROVISIONAL — generated by this
 * implementation, guarding against drift — and must be cross-checked against
 * covclaimd's reference vectors before production use (see the README and
 * TODO(claim-packet-vectors) in the source).
 */
import { describe, expect, it, vi } from "vitest";
import { base64, hex } from "@scure/base";
import { secp256k1 } from "@noble/curves/secp256k1.js";

import { sealClaimPacket } from "../src/claimPacket";
import {
    claimPacketHex,
    openClaimPacket,
    sealClaimPacketDeterministic,
} from "./helpers/claimPacket";

const PREIMAGE = new Uint8Array(32).fill(7);
const COVCLAIMD_SK = new Uint8Array(32).fill(0x22);
const COVCLAIMD_PK = secp256k1.getPublicKey(COVCLAIMD_SK, true);

const deterministic = () =>
    sealClaimPacketDeterministic(
        {
            preimage: PREIMAGE,
            covclaimdPubkey: COVCLAIMD_PK,
        },
        new Uint8Array(32).fill(0x11),
        new Uint8Array(12).fill(0x0a),
    );

describe("sealClaimPacket", () => {
    it("produces the pinned wire bytes for the fixed ephemeral key and nonce", async () => {
        const packet = await deterministic();
        expect(claimPacketHex(packet.ciphertext)).toBe(
            "034f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa" + // ephPub(33)
                "0a0a0a0a0a0a0a0a0a0a0a0a" + // nonce(12)
                "14ec375e22b0f016fb127e4740e9599f6b07d04bd040751d9fade4c5427b9787" +
                "915a33390ddb0d72093c69eff4d6a335", // ciphertext ‖ GCM tag
        );
    });

    it("round-trips: covclaimd's key recovers exactly P", async () => {
        const packet = await deterministic();
        const opened = await openClaimPacket(packet.ciphertext, COVCLAIMD_SK);
        expect(hex.encode(opened)).toBe(hex.encode(PREIMAGE));
    });

    it("authenticates: a tampered ciphertext refuses to open", async () => {
        const packet = await deterministic();
        const bytes = hex.decode(claimPacketHex(packet.ciphertext));
        bytes[50] ^= 0x01;
        await expect(openClaimPacket(base64.encode(bytes), COVCLAIMD_SK)).rejects.toThrow();
    });

    it("rejects malformed inputs", async () => {
        await expect(
            sealClaimPacket({
                preimage: PREIMAGE.slice(1),
                covclaimdPubkey: COVCLAIMD_PK,
            }),
        ).rejects.toThrow(/32 bytes/);
        await expect(
            sealClaimPacket({
                preimage: PREIMAGE,
                covclaimdPubkey: COVCLAIMD_PK.slice(1),
            }),
        ).rejects.toThrow(/compressed/);
        await expect(
            sealClaimPacketDeterministic(
                {
                    preimage: PREIMAGE,
                    covclaimdPubkey: COVCLAIMD_PK,
                },
                new Uint8Array(32).fill(0x11),
                new Uint8Array(11),
            ),
        ).rejects.toThrow(/12 bytes/);
    });

    // Hermes has no `crypto.subtle`; the suite otherwise runs only where it exists.
    it("seals without crypto.subtle", async () => {
        const { getRandomValues } = globalThis.crypto;
        vi.stubGlobal("crypto", {
            getRandomValues: getRandomValues.bind(globalThis.crypto),
        });
        const packet = await (async () => {
            try {
                expect(globalThis.crypto.subtle).toBeUndefined();
                return await sealClaimPacket({
                    preimage: PREIMAGE,
                    covclaimdPubkey: COVCLAIMD_PK,
                });
            } finally {
                vi.unstubAllGlobals();
            }
        })();
        const opened = await openClaimPacket(packet.ciphertext, COVCLAIMD_SK);
        expect(hex.encode(opened)).toBe(hex.encode(PREIMAGE));
    });

    it("fresh randomness per packet: two seals of the same P differ", async () => {
        const a = await sealClaimPacket({
            preimage: PREIMAGE,
            covclaimdPubkey: COVCLAIMD_PK,
        });
        const b = await sealClaimPacket({
            preimage: PREIMAGE,
            covclaimdPubkey: COVCLAIMD_PK,
        });
        expect(a.ciphertext).not.toBe(b.ciphertext);
    });
});
